
[tasks.echo]
script = "echo hello world"

[tasks.flow]
run_task = "echo"
condition_script = ["exit 0"]

[tasks.echo1]
command = "echo"
args = ["1"]

[tasks.echo2]
command = "echo"
args = ["2"]

[tasks.simple-multi]
run_task = { name = ["echo1", "echo2"] }

[tasks.routing-multi]
run_task = [{ name = ["echo1", "echo2"] }]

[tasks.parallel-multi]
run_task = { name = ["echo1", "echo2"], parallel = true }

[tasks.fail]
script = "exit 1"

[tasks.cleanup]
command = "echo"
args = ["cleanup"]

[tasks.cleanup-example]
run_task = { name = ["echo1", "echo2"], fork = true, cleanup_task = "cleanup" }

[tasks.cleanup-example-with-error]
run_task = { name = [
  "echo1",
  "echo2",
  "fail",
], fork = true, cleanup_task = "cleanup" }
