
[tasks.echo]
env = { "ECHO_TEST" = "ECHO_ENV" }
script = '''
echo watch triggered
echo ECHO_TEST: ${ECHO_TEST}
echo CARGO_MAKE_DISABLE_WATCH: ${CARGO_MAKE_DISABLE_WATCH}
'''
watch = true

[tasks.watch-example]
command = "echo"
args = ["Triggered by watch"]
watch = true

[tasks.watch-args-example]
command = "echo"
args = ["Triggered by watch"]
watch = { postpone = true, no_git_ignore = true, ignore_pattern = "examples/files/*", watch = [
  "./docs/",
] }
